((date . "Sat Sep 12 13:21:07 2026") (chez . "Chez Scheme Version 10.0.0")
  (machine-type . ta6le) (llvm 16 0 6)
  (installation . "/usr/lib/llvm-16")
  (shared-object . "/usr/lib/llvm-16/lib/libLLVM-16.so")
  (shared-object-suffix . "so")
  (headers . "/usr/lib/llvm-16/include/llvm-c")
  (headers-validated . #t)
  (default-triple . "x86_64-pc-linux-gnu")
  (native-target . "X86") (native-object-format . elf)
  (llvm-host-cpu . "generic"))
