((date . "Sat Sep 12 13:21:08 2026") (chez . "Chez Scheme Version 10.0.0")
  (machine-type . ta6le) (llvm 19 1 7)
  (installation . "/usr/lib/llvm-19")
  (shared-object . "/usr/lib/llvm-19/lib/libLLVM-19.so")
  (shared-object-suffix . "so")
  (headers . "/usr/lib/llvm-19/include/llvm-c")
  (headers-validated . #t)
  (default-triple . "x86_64-pc-linux-gnu")
  (native-target . "X86") (native-object-format . elf)
  (llvm-host-cpu . "znver5"))
