((date . "Sat Sep 12 12:16:11 2026") (chez . "Chez Scheme Version 10.0.0")
  (machine-type . ta6le) (llvm 20 1 8)
  (installation . "/usr/lib/llvm-20")
  (shared-object . "/usr/lib/llvm-20/lib/libLLVM-20.so")
  (shared-object-suffix . "so")
  (headers . "/usr/lib/llvm-20/include/llvm-c")
  (headers-validated . #t)
  (default-triple . "x86_64-pc-linux-gnu")
  (native-target . "X86") (native-object-format . elf)
  (llvm-host-cpu . "znver5"))
