;;; hello-portable.ss -- the SchemeLL answer to "how do I write a
;;; freestanding hello for MORE than one platform?": sll programs are
;;; plain data, so the portable 99% is written once and the per-ABI 1%
;;; (raw syscalls: instruction, registers, and numbers all differ per
;;; kernel/ISA) is generated by an ordinary Scheme function.
;;;
;;; This script cross-compiles the SAME source to objects for both
;;; Linux ISAs -- the AArch64 one from an x86 host and vice versa.
;;; Run with: scheme --libdirs . --script examples/aot/hello-portable.ss
(import (chezscheme)
        (prefix (sll) sll:)
        (prefix (llvm ir) ir:)
        (prefix (llvm target) target:))

;; the per-kernel-ABI tail: write(1, buf, len) then exit_group(0)
(define (syscall-write+exit abi buf len)
  (case abi
    [(linux-x86_64)
     `((call i64 ((asm "syscall"
                       "={rax},{rax},{rdi},{rsi},{rdx},~{rcx},~{r11},~{memory}"
                       sideeffect)
                  (i64 1) (i64 1) (ptr ,buf) (i64 ,len)))
       (call i64 ((asm "syscall" "={rax},{rax},{rdi},~{rcx},~{r11}"
                       sideeffect)
                  (i64 231) (i64 0))))]
    [(linux-aarch64)
     `((call i64 ((asm "svc #0" "={x0},{x8},{x0},{x1},{x2},~{memory}"
                       sideeffect)
                  (i64 64) (i64 1) (ptr ,buf) (i64 ,len)))
       (call i64 ((asm "svc #0" "={x0},{x8},{x0}" sideeffect)
                  (i64 94) (i64 0))))]
    [else (error 'hello-portable "no syscall convention for" abi)]))

;; the portable 99%: identical for every target
(define (hello-prog abi)
  `((define void (@_start)
      (label %entry
        (= %buf (alloca (array 24 i8) (align 8)))
        (store (i64 5989836361474794824) (ptr %buf) (align 8))   ; "Hello, S"
        (= %p8 (getelementptr i8 (ptr %buf) (i64 8)))
        (store (i64 2399376699992402019) (ptr %p8) (align 8))    ; "chemeLL!"
        (= %p16 (getelementptr i8 (ptr %buf) (i64 16)))
        (store (i8 10) (ptr %p16))
        ,@(syscall-write+exit abi '%buf 17)
        (unreachable)))))

(define targets
  '((linux-x86_64 "x86_64-unknown-linux-gnu" "X86" "/tmp/hello-x86_64.o")
    (linux-aarch64 "aarch64-unknown-linux-gnu" "AArch64"
                   "/tmp/hello-aarch64.o")))

(for-each
  (lambda (t)
    (let ([abi (car t)] [triple (cadr t)]
          [backend (caddr t)] [out (cadddr t)])
      (printf "~%=== ~a: generated syscall tail ===~%" abi)
      (for-each (lambda (f) (printf "  ~s~%" f))
                (syscall-write+exit abi '%buf 17))
      (if (target:initialize-target! backend)
          (let* ([ctx (ir:make-context)]
                 [m (sll:build ctx (symbol->string abi) (hello-prog abi))]
                 [tm (target:make-machine triple "generic" "" 'default)])
            (ir:verify-module m)
            (ir:set-module-target-triple! m triple)
            (target:emit-object-file tm m out)
            (printf "  -> ~a~%" out))
          (printf "  (this libLLVM has no ~a backend; skipped)~%" backend))))
  targets)

(printf "~%Both objects came from ONE source; only the generated tail~%")
(printf "differs. For the host target, sllc --exe turns the x86-64 one~%")
(printf "into a standalone executable (see hello-linux-x86.sll).~%")
