((date . "Sat Sep 12 13:36:02 2026") (chez . "Chez Scheme Version 10.4.0")
  (machine-type . ta6fb) (llvm 20 1 8)
  (installation . "/usr/local/llvm20")
  (shared-object . "/usr/local/llvm20/lib/libLLVM-20.so")
  (shared-object-suffix . "so")
  (headers . "/usr/local/llvm20/include/llvm-c")
  (headers-validated . #t)
  (default-triple . "x86_64-portbld-freebsd15.0")
  (native-target . "X86") (native-object-format . elf)
  (llvm-host-cpu . "znver4"))
