((date . "Sat Sep 12 13:35:59 2026") (chez . "Chez Scheme Version 10.4.0")
  (machine-type . ta6fb) (llvm 16 0 6)
  (installation . "/usr/local/llvm16")
  (shared-object . "/usr/local/llvm16/lib/libLLVM-16.so")
  (shared-object-suffix . "so")
  (headers . "/usr/local/llvm16/include/llvm-c")
  (headers-validated . #t)
  (default-triple . "x86_64-portbld-freebsd15.0")
  (native-target . "X86") (native-object-format . elf)
  (llvm-host-cpu . "znver4"))
