((date . "Sat Sep 12 13:36:01 2026") (chez . "Chez Scheme Version 10.4.0")
  (machine-type . ta6fb) (llvm 19 1 7)
  (installation . "/usr/local/llvm19")
  (shared-object . "/usr/local/llvm19/lib/libLLVM-19.so")
  (shared-object-suffix . "so")
  (headers . "/usr/local/llvm19/include/llvm-c")
  (headers-validated . #t)
  (default-triple . "x86_64-portbld-freebsd15.0")
  (native-target . "X86") (native-object-format . elf)
  (llvm-host-cpu . "znver4"))
